testthat::test_that("Ensure named works", {
    test_list.unnamed <- list(1, 2, 3, 4)
    test_list.named <- ensure_named(test_list.unnamed, prefix = "g_")
    expect_length(test_list.named, length(test_list.unnamed))
    expect_named(test_list.named, c("g_1", "g_2", "g_3", "g_4"))
    test_list.named <- list(a = 1, b = 2, c = 3, d = 4)
    test_list.ensured <- ensure_named(test_list.named, prefix = "g_")
    expect_length(test_list.ensured, length(test_list.named))
    expect_named(test_list.ensured, names(test_list.named))
})
